# Generated by Django 4.0.4 on 2022-06-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtrade', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
