# Generated by Django 4.0.4 on 2022-06-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtrade', '0004_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
